picapp/urls.py
from django.urls import path
from . import views
app_name = 'picapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('pic', views.index2, name='index2'),


]

picatweets/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('picapp.urls'),),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

picapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
import tweepy
from tweepy import OAuthHandler
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json

consumer_key = ''
consumer_secret = ''
access_token = ''
access_secret = ''
auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

 
def index(request):


    api = tweepy.API(auth, wait_on_rate_limit=True,wait_on_rate_limit_notify=True)
    
    search_tweets = api.search(q="#IncendiosForestales OR #IFF OR #incendioForestal OR #Bosques ", lang="es", count=200, include_rts = True,  tweet_mode = 'extended')
    search_tweets_noRT = api.search(q="#IncendiosForestales OR #IFF OR #incendioForestal OR #Bosques -filter:retweets", lang="es", count=200, include_rts = True,  tweet_mode = 'extended')
    user_metions = api.mentions_timeline(tweet_mode = 'extended') 

    return render(request, 'picapp/index.html', {'search_tweets': search_tweets, 'search_tweets_noRT':search_tweets_noRT,'user_metions':user_metions})


def index2(request):
    api = tweepy.API(auth, wait_on_rate_limit=True,wait_on_rate_limit_notify=True)
    more_tweets1 = api.search(q="#afforestation OR #deforestation OR #ClimateAction  -filter:retweets", lang="es", count=200, include_rts = True,  tweet_mode = 'extended')
    more_tweets2 = api.search(q="#climatechange OR #biodiversity OR #amenazas OR #deforestación -filter:retweets", lang="es", count=200, include_rts = True,  tweet_mode = 'extended')
    more_tweets3 = api.search(q="#trees OR #IFF OR #forest OR #amenazas OR #woods -filter:retweets", lang="es", count=200, include_rts = True,  tweet_mode = 'extended')

    return render(request, 'picapp/index2.html', {'more_tweets1': more_tweets1, 'more_tweets2':more_tweets2,'more_tweets3':more_tweets3})

picapp/templates/picapp/index.html
<html>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  <style>
  .column {
  float: left;
  width: 33.33%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

    </style>
  <body>
<br>
<div class="w3-container">

<a href="{% url "picapp:index2" %}" style="float: right;color: rgba(255, 146, 202, 0.845);">pica más tweets</a> 
</div>
        <div class="w3-container">
        <br>
        <div class="row">
          <div class="column" style="background-color:rgb(255, 255, 255);">
            <h4>#IncendiosForestales, #IIFF,  #incendioForestal, #Bosques</h4>
            {% for tweepy in search_tweets %}
            <div class="w3-panel w3-card">
              <p>{{ tweepy.full_text }}</p>
              <p style="color: rgb(103, 103, 103);font-size: small;">retweet count:{{ tweepy.retweet_count }}<br>
                likes:{{ tweepy.favorite_count }}<br>
              {{ tweepy.created_at }}</p>              
              <h6 style="color: rgb(103, 103, 103);font-size: small;">{{ tweepy.place.full_name }}</h6>

              <h6><a target="_blank" rel="noopener noreferrer" href="{{ tweepy.user.url }}"><strong>source</strong></a></h6>
            </div>
            {% endfor %}
          </div>
          <div class="column" style="background-color:rgb(255, 255, 255);">
            <h4>#StopIncendios OR #incendios OR #Campo OR #MedioAmbiente </h4>
            {% for tweepy in search_tweets_noRT %}
            <div class="w3-panel w3-card">
              <p>{{ tweepy.full_text }}</p>

              <p style="color: rgb(103, 103, 103);font-size: small;">retweet count:{{ tweepy.retweet_count }}<br>
                likes:{{ tweepy.favorite_count }}<br>
              {{ tweepy.created_at }}</p>
              <h6 style="color: rgb(103, 103, 103);font-size: small;">{{ tweepy.place.full_name }}</h6>

              <h6><a target="_blank" rel="noopener noreferrer" href="{{ tweepy.user.url }}"><strong>source</strong></a></h6>
            </div>
            {% endfor %}
          </div>
          <div class="column" style="background-color:rgb(255, 255, 255);">
            <h4>FENIX Mentions  </h4>
            {% for tweepy in user_metions %}
            <div class="w3-panel w3-card">
              <p>{{ tweepy.full_text }}</p>
              <p style="color: rgb(103, 103, 103);font-size: small;">retweet count:{{ tweepy.retweet_count }}<br>
                likes:{{ tweepy.favorite_count }}<br>
              {{ tweepy.created_at }}</p>
                            <h6 style="color: rgb(103, 103, 103);font-size: small;">{{ tweepy.place.full_name }}</h6>
            <h6><a target="_blank" rel="noopener noreferrer" href="{{ tweepy.user.url }}"><strong>source</strong></a></h6>
            
            </div>
            {% endfor %}
          </div>
        </div>
        

      </div>
      


  

  </body>
</html>

picapp/templates/picapp/index2.html
<html>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  <style>
  .column {
  float: left;
  width: 33.33%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

    </style>
  <body>

      <div class="w3-container">
        <div class="row">
          <div class="column" style="background-color:rgb(255, 255, 255);">
            <h4>#afforestation OR #ClimateAction OR #deforestación</h3>
            {% for tweepy in more_tweets1 %}
            <div class="w3-panel w3-card">
                <p>{{ tweepy.full_text }}</p>
                <p style="color: rgb(103, 103, 103);font-size: small;">retweet count:{{ tweepy.retweet_count }}<br>
                    likes:{{ tweepy.favorite_count }}<br>
                    {{ tweepy.created_at }}</p>
                <h6 style="color: rgb(103, 103, 103);font-size: small;">{{ tweepy.place.full_name }}</h6>
                <h6><a target="_blank" rel="noopener noreferrer" href="{{ tweepy.user.url }}"><strong>source</strong></a></h6>
            </div>
            {% endfor %}
          </div>
          <div class="column" style="background-color:rgb(255, 255, 255);">
            <h4>#climatechange OR #biodiversity OR #amenazas OR #deforestación</h4>
           
            {% for tweepy in more_tweets2 %}
            <div class="w3-panel w3-card">
            <p>{{ tweepy.full_text }}</p>
            <p style="color: rgb(103, 103, 103);font-size: small;">retweet count:{{ tweepy.retweet_count }}<br>
                likes:{{ tweepy.favorite_count }}<br>
                {{ tweepy.created_at }}</p>
            <h6 style="color: rgb(103, 103, 103);font-size: small;">{{ tweepy.place.full_name }}</h6>
            <h6><a target="_blank" rel="noopener noreferrer" href="{{ tweepy.user.url }}"><strong>source</strong></a></h6>
        </div>
            {% endfor %}
          </div>
          <div class="column" style="background-color:rgb(255, 255, 255);">
            <h4>#trees OR #wood OR #forest</h4>
            {% for tweepy in more_tweets1 %}
            <div class="w3-panel w3-card">
                <p>{{ tweepy.full_text }}</p>
                <p style="color: rgb(103, 103, 103);font-size: small;">retweet count:{{ tweepy.retweet_count }}<br>
                    likes:{{ tweepy.favorite_count }}<br>
                    {{ tweepy.created_at }}</p>
                <h6 style="color: rgb(103, 103, 103);font-size: small;">{{ tweepy.place.full_name }}</h6>
                <h6><a target="_blank" rel="noopener noreferrer" href="{{ tweepy.user.url }}"><strong>source</strong></a></h6>
            </div>
            {% endfor %}
          </div>
        </div>
        

      </div>
      
  </body>
</html>